version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/home/sadmin/laravel_learn/public/

  mysql:
    image: mysql:5.7.29
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD:
    # volumes: 
    #   - dbdata:/var/lib/mysql

  php:
    build: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/home/sadmin/laravel_learn
    working_dir: /home/sadmin/laravel_learn

# volumes:
#   dbdata:
